### ISSUE TITLE
Sounds repeat until snd_restart

### ISSUE THREAD

**Issue by hemebond** [fte-team/fteqw#181] opened 2023-05-30 06:25 UTC
Running `fteqw-sdl2` (including built from latest main branch), when I load a new map, or map_restart, all sounds being played will start looping infinitely, e.g., jumping, shooting, menus, etc. I have to `snd_restart` to fix it, and do it every time a map is started.

**Comment by hemebond** [comment] 2023-06-02 16:35
That resolved the issue. Thank you.

**Comment by Xylemon** [comment] 2023-06-24 03:57
Closing as this is technically a duplicate of #170

**Closed by Xylemon** 2023-06-24 03:57 UTC

**Comment by hemebond** [comment] 2025-07-16 08:49
@Xylemon Just a heads-up, this is still a problem. I had to find this issue to get the solution again.
